services:
  - type: web
    name: car-dealership-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn capstone_project.wsgi:application
    preDeployCommand: python manage.py migrate
    envVars:
      - key: DEBUG
        value: "False"  # Set to "True" only for testing, not in production
      - key: SECRET_KEY
        value: your-production-secret-key
      - key: EXPRESS_API_URL
        value: https://car-dealership-express-api.onrender.com
